# Generated by Django 6.0.3 on 2026-03-10 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("romance", "Romance"),
                            ("scifi", "Sci-Fi"),
                            ("thriller", "Thriller"),
                            ("animation", "Animation"),
                        ],
                        default="action",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("hindi", "Hindi"),
                            ("tamil", "Tamil"),
                            ("telugu", "Telugu"),
                            ("others", "Others"),
                        ],
                        default="english",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("total_rows", models.PositiveIntegerField(default=8)),
                ("seats_per_row", models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_date", models.DateField()),
                ("show_time", models.TimeField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="movies.movie",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="movies.screen",
                    ),
                ),
            ],
            options={
                "ordering": ["show_date", "show_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="movies.show",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="screen",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screens",
                to="movies.theater",
            ),
        ),
        migrations.CreateModel(
            name="SeatBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_letter", models.CharField(max_length=2)),
                ("seat_number", models.PositiveIntegerField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="movies.booking",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "row_letter", "seat_number")},
            },
        ),
    ]
