# Generated by Django 6.0.3 on 2026-03-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("scifi", "Sci-Fi"),
                    ("thriller", "Thriller"),
                    ("animation", "Animation"),
                ],
                db_index=True,
                default="action",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("hindi", "Hindi"),
                    ("tamil", "Tamil"),
                    ("telugu", "Telugu"),
                    ("others", "Others"),
                ],
                db_index=True,
                default="english",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["genre", "language"], name="movies_movi_genre_08a05d_idx"
            ),
        ),
    ]
