# Generated by Django 6.0.3 on 2026-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_genre_alter_movie_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True, help_text="YouTube trailer URL", max_length=500, null=True
            ),
        ),
    ]
