# Generated by Django 6.0.3 on 2026-03-19 06:14

import django.db.models.deletion
import movies.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_trailer_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Amount in paise (INR × 100)"
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Order Created"),
                            ("success", "Payment Successful"),
                            ("failed", "Payment Failed"),
                            ("timeout", "Payment Timed Out"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("signature_verified", models.BooleanField(default=False)),
                (
                    "idempotency_key",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeatLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_letter", models.CharField(max_length=2)),
                ("seat_number", models.PositiveIntegerField()),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=movies.models.seat_lock_expiry),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="razorpay_order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Payment Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="movies_book_status_5cd60b_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["razorpay_order_id"], name="movies_book_razorpa_c33f2e_idx"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="movies.booking",
            ),
        ),
        migrations.AddField(
            model_name="seatlock",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_locks",
                to="movies.show",
            ),
        ),
        migrations.AddField(
            model_name="seatlock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_locks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["razorpay_order_id"], name="movies_paym_razorpa_39457f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["idempotency_key"], name="movies_paym_idempot_c2c7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="movies_paym_status_5316c9_idx"),
        ),
        migrations.AddIndex(
            model_name="seatlock",
            index=models.Index(
                fields=["show", "expires_at"], name="movies_seat_show_id_500d5e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seatlock",
            unique_together={("show", "row_letter", "seat_number")},
        ),
    ]
